# Generated by Django 4.1.2 on 2022-10-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('job', 'Job'), ('story', 'Story'), ('comment', 'Comment'), ('poll', 'Poll'), ('pollopt', 'PollOpt')], max_length=10)),
                ('by', models.CharField(blank=True, max_length=50)),
                ('time', models.IntegerField(blank=True)),
                ('parent', models.IntegerField(blank=True)),
                ('text', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-time'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('job', 'Job'), ('story', 'Story'), ('comment', 'Comment'), ('poll', 'Poll'), ('pollopt', 'PollOpt')], max_length=10)),
                ('by', models.CharField(blank=True, max_length=50)),
                ('time', models.IntegerField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('title', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-time'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('job', 'Job'), ('story', 'Story'), ('comment', 'Comment'), ('poll', 'Poll'), ('pollopt', 'PollOpt')], max_length=10)),
                ('by', models.CharField(blank=True, max_length=50)),
                ('time', models.IntegerField(blank=True)),
                ('descendants', models.IntegerField(blank=True)),
                ('score', models.IntegerField(blank=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-time'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('job', 'Job'), ('story', 'Story'), ('comment', 'Comment'), ('poll', 'Poll'), ('pollopt', 'PollOpt')], max_length=10)),
                ('by', models.CharField(blank=True, max_length=50)),
                ('time', models.IntegerField(blank=True)),
                ('parent', models.IntegerField(blank=True)),
                ('text', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-time'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('job', 'Job'), ('story', 'Story'), ('comment', 'Comment'), ('poll', 'Poll'), ('pollopt', 'PollOpt')], max_length=10)),
                ('by', models.CharField(blank=True, max_length=50)),
                ('time', models.IntegerField(blank=True)),
                ('descendants', models.IntegerField(blank=True)),
                ('score', models.IntegerField(blank=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True, default='http://stoplight.io/prism/')),
            ],
            options={
                'ordering': ['-time'],
                'abstract': False,
            },
        ),
    ]
