# Generated by Django 4.1.2 on 2022-10-30 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_item_delete_job_delete_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('type', models.CharField(choices=[('job', 'Job'), ('story', 'Story'), ('comment', 'Comment'), ('poll', 'Poll'), ('pollopt', 'PollOpt')], max_length=10)),
                ('by', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-time'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('type', models.CharField(choices=[('job', 'Job'), ('story', 'Story'), ('comment', 'Comment'), ('poll', 'Poll'), ('pollopt', 'PollOpt')], max_length=10)),
                ('by', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('descendants', models.IntegerField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, default='http://stoplight.io/prism/', null=True)),
            ],
            options={
                'ordering': ['-time'],
                'abstract': False,
            },
        ),
    ]
