# Generated by Django 4.1.2 on 2022-11-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_job_story'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('job', 'Job'), ('story', 'Story')], max_length=10),
        ),
        migrations.AlterField(
            model_name='story',
            name='type',
            field=models.CharField(choices=[('job', 'Job'), ('story', 'Story')], max_length=10),
        ),
    ]
